package com.dev_poc.multi_instance;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class PersonBooking implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String bookingReference;
	private java.lang.String firstName;
	private java.lang.String surname;
	private java.lang.String frequentFlyerNumber;
	private java.lang.String frequentFlyerProgramme;
	private java.lang.String mobileNumber;
	private java.lang.String emailAddress;

	public PersonBooking() {
	}

	public java.lang.String getBookingReference() {
		return this.bookingReference;
	}

	public void setBookingReference(java.lang.String bookingReference) {
		this.bookingReference = bookingReference;
	}

	public java.lang.String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(java.lang.String firstName) {
		this.firstName = firstName;
	}

	public java.lang.String getSurname() {
		return this.surname;
	}

	public void setSurname(java.lang.String surname) {
		this.surname = surname;
	}

	public java.lang.String getFrequentFlyerNumber() {
		return this.frequentFlyerNumber;
	}

	public void setFrequentFlyerNumber(java.lang.String frequentFlyerNumber) {
		this.frequentFlyerNumber = frequentFlyerNumber;
	}

	public java.lang.String getFrequentFlyerProgramme() {
		return this.frequentFlyerProgramme;
	}

	public void setFrequentFlyerProgramme(
			java.lang.String frequentFlyerProgramme) {
		this.frequentFlyerProgramme = frequentFlyerProgramme;
	}

	public java.lang.String getMobileNumber() {
		return this.mobileNumber;
	}

	public void setMobileNumber(java.lang.String mobileNumber) {
		this.mobileNumber = mobileNumber;
	}

	public java.lang.String getEmailAddress() {
		return this.emailAddress;
	}

	public void setEmailAddress(java.lang.String emailAddress) {
		this.emailAddress = emailAddress;
	}

	public PersonBooking(java.lang.String bookingReference,
			java.lang.String firstName, java.lang.String surname,
			java.lang.String frequentFlyerNumber,
			java.lang.String frequentFlyerProgramme,
			java.lang.String mobileNumber, java.lang.String emailAddress) {
		this.bookingReference = bookingReference;
		this.firstName = firstName;
		this.surname = surname;
		this.frequentFlyerNumber = frequentFlyerNumber;
		this.frequentFlyerProgramme = frequentFlyerProgramme;
		this.mobileNumber = mobileNumber;
		this.emailAddress = emailAddress;
	}

}