package com.dev_poc.multi_instance;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ScheduledFlight implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String flightNumber;
	private java.lang.String airlineCode;
	private String scheduledDate;
	private String scheduledTime;
	private java.lang.String timezone;
	private java.lang.String flightStatus;
	private java.util.List<com.dev_poc.multi_instance.PersonBooking> passengerManifest;

	public ScheduledFlight() {
	}

	public java.lang.String getFlightNumber() {
		return this.flightNumber;
	}

	public void setFlightNumber(java.lang.String flightNumber) {
		this.flightNumber = flightNumber;
	}

	public java.lang.String getAirlineCode() {
		return this.airlineCode;
	}

	public void setAirlineCode(java.lang.String airlineCode) {
		this.airlineCode = airlineCode;
	}

	public java.lang.String getTimezone() {
		return this.timezone;
	}

	public void setTimezone(java.lang.String timezone) {
		this.timezone = timezone;
	}

	public java.lang.String getFlightStatus() {
		return this.flightStatus;
	}

	public void setFlightStatus(java.lang.String flightStatus) {
		this.flightStatus = flightStatus;
	}

	public java.util.List<com.dev_poc.multi_instance.PersonBooking> getPassengerManifest() {
		return this.passengerManifest;
	}

	public void setPassengerManifest(
			java.util.List<com.dev_poc.multi_instance.PersonBooking> passengerManifest) {
		this.passengerManifest = passengerManifest;
	}

	public java.lang.String getScheduledDate() {
		return this.scheduledDate;
	}

	public void setScheduledDate(java.lang.String scheduledDate) {
		this.scheduledDate = scheduledDate;
	}

	public java.lang.String getScheduledTime() {
		return this.scheduledTime;
	}

	public void setScheduledTime(java.lang.String scheduledTime) {
		this.scheduledTime = scheduledTime;
	}

	public ScheduledFlight(
			java.lang.String flightNumber,
			java.lang.String airlineCode,
			java.lang.String scheduledDate,
			java.lang.String scheduledTime,
			java.lang.String timezone,
			java.lang.String flightStatus,
			java.util.List<com.dev_poc.multi_instance.PersonBooking> passengerManifest) {
		this.flightNumber = flightNumber;
		this.airlineCode = airlineCode;
		this.scheduledDate = scheduledDate;
		this.scheduledTime = scheduledTime;
		this.timezone = timezone;
		this.flightStatus = flightStatus;
		this.passengerManifest = passengerManifest;
	}

}